default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  username: root
  password: Gallo.23gallogol
  host: localhost
  database: FootSpaPodologos_development

test:
  <<: *default
  username: root
  password: Gallo.23gallogol
  host: localhost
  database: FootSpaPodologos_test

production:
  <<: *default
  database: db/production.sqlite3
